-- CreateEnum
CREATE TYPE "Rank" AS ENUM ('BRONZE', 'SILVER', 'GOLD', 'PLATINUM', 'DIAMOND', 'MASTER');

-- AlterTable
ALTER TABLE "User"
ADD COLUMN "avatar" TEXT,
ADD COLUMN "level" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN "xp" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "rank" "Rank" NOT NULL DEFAULT 'BRONZE',
ADD COLUMN "wins" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "losses" INTEGER NOT NULL DEFAULT 0;

-- CreateIndex
CREATE INDEX "User_rank_idx" ON "User"("rank");
